vmwgfx: fix missing array notation
 Fixes error identified by gcc-12.1.0 compiler

make
  CC       libvmwgfx_la-vmwgfx_tex_video.lo
vmwgfx_tex_video.c: In function 'stop_video':
vmwgfx_tex_video.c:240:20: error: the comparison will always evaluate as 'true' for the address of 'yuv' will never be NULL [-Werror=address]
  240 |                if (priv->yuv[i]) {
      |                    ^~~~